name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: [Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
